language: python
python:
- 3.6
env:
  # TODO(luke): Keep this in-sync with .env and app.yaml
- BROWSER=none GOOGLE_APPLICATION_CREDENTIALS='credentials/elvo-7136c1299dea.json' SPREADSHEET_CREDENTIALS='credentials/elvo-de539f4b4cd3.json'
before_install:
- openssl aes-256-cbc -K $encrypted_5dacdc162043_key -iv $encrypted_5dacdc162043_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
install:
- pip install -r requirements.txt
- pip install flake8 pytest pytest-cov codecov
script:
- flake8 .
- pytest --cov=./
after_success:
- codecov
