runtime: python
env: flex
entrypoint: gunicorn -b :$PORT -w 4 main:app

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1

# TODO: Keep this synced with .env, becasue of how skip_files works
# we will need both of these
env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: 'credentials/elvo-7136c1299dea.json'
  SPREADSHEET_CREDENTIALS: 'credentials/elvo-de539f4b4cd3.json'

resources:
  cpu: 1
  memory_gb: 6

skip_files:
- venv/
- node_modules/
