runtime: python
env: flex
entrypoint: gunicorn -b :$PORT -w 4 main:app

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 6

skip_files:
- venv/
- node_modules/
